language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.081.2
    - d: dmd-2.080.1
    - d: dmd-2.079.1
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libclang-3.9-dev
      - g++-7
      - libx11-dev
      - libxcomposite-dev
      - libxinerama-dev


script:
  - ./ci.sh

